# https://taskfile.dev

version: '3'

dotenv: ['.env.sh']

tasks:
  default:
    cmds:
      - clear
      - goreleaser build --snapshot --clean
      - tree dist
    silent: true

  # Quick development tasks
  test:
    desc: Test the MCP server with a simple greet command
    cmds:
      - go run ./cmd/test_client greet '{"name":"Developer"}'

  test-argo:
    desc: Test the ArgoCD list_clusters tool
    cmds:
      - go run ./cmd/test_client argocd_list_clusters '{}'

  test-custom:
    desc: "Test a custom tool (usage: task test-custom TOOL=tool_name ARGS='{\"key\":\"value\"}')"
    cmds:
      - go run ./cmd/test_client {{.TOOL}} '{{.ARGS}}'

  dev:
    desc: Run the server directly and tail logs (for manual testing)
    cmds:
      - |
        # Start tailing logs in background
        tail -f /tmp/bw-mcp/log.txt 2>/dev/null &
        TAIL_PID=$!
        
        # Trap to kill tail on exit
        trap "kill $TAIL_PID 2>/dev/null" EXIT
        
        # Run the server
        go run ./cmd/mcp_server
        
        # Cleanup tail process
        kill $TAIL_PID 2>/dev/null
